### ISSUE TITLE
Evaluate vault BSL dependency

### ISSUE THREAD

**Issue by jaxxstorm** [pulumiverse/pulumi-dynatrace#50]
This provider takes a dependency on the HashiCorp vault provider. Do not release any versions until this is addressed

**Comment by jaxxstorm** [comment]
cc @williamsbdev

**Comment by pierskarsenbarg** [comment]
v1.12.0 is pre-BSL.

Same version as in the pulumi/pulumi/pkg module: https://github.com/pulumi/pulumi/blob/8476c3f7f5c98534139769ec02c31206e3a09e4d/pkg/go.mod#L193
